CREATE TABLE EMPLOYEE(
  EMPLOYEE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LAST_NAME VARCHAR(64),
  FIRST_NAME VARCHAR(64),
  DOB DATE,
  EMAIL_ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(40),
  ADDRESS VARCHAR(100),
  STATE VARCHAR(2),
  TELEPHONE VARCHAR(30)
);

